name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # Or your main branch name (e.g., main)

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app (inject API key)
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages # The branch where GitHub Pages will be served from
          folder: dist # The output folder from your build process